
        iPartikkel1Samplepos1_indx chnget  "iPartikkel1Samplepos1"
        kPartikkel1Samplepos1 table iPartikkel1Samplepos1_indx, giSinglePreset
        chnset kPartikkel1Samplepos1, "Partikkel1Samplepos1"
        iPartikkel1Samplepos2_indx chnget  "iPartikkel1Samplepos2"
        kPartikkel1Samplepos2 table iPartikkel1Samplepos2_indx, giSinglePreset
        chnset kPartikkel1Samplepos2, "Partikkel1Samplepos2"
        iPartikkel1Samplepos3_indx chnget  "iPartikkel1Samplepos3"
        kPartikkel1Samplepos3 table iPartikkel1Samplepos3_indx, giSinglePreset
        chnset kPartikkel1Samplepos3, "Partikkel1Samplepos3"
        iPartikkel1Samplepos4_indx chnget  "iPartikkel1Samplepos4"
        kPartikkel1Samplepos4 table iPartikkel1Samplepos4_indx, giSinglePreset
        chnset kPartikkel1Samplepos4, "Partikkel1Samplepos4"
        iPartikkel1Amp_indx chnget  "iPartikkel1Amp"
        kPartikkel1Amp table iPartikkel1Amp_indx, giSinglePreset
        chnset kPartikkel1Amp, "Partikkel1Amp"
        iPartikkel1SyncGravity_indx chnget  "iPartikkel1SyncGravity"
        kPartikkel1SyncGravity table iPartikkel1SyncGravity_indx, giSinglePreset
        chnset kPartikkel1SyncGravity, "Partikkel1SyncGravity"
        iPartikkel1GrainRate_indx chnget  "iPartikkel1GrainRate"
        kPartikkel1GrainRate table iPartikkel1GrainRate_indx, giSinglePreset
        chnset kPartikkel1GrainRate, "Partikkel1GrainRate"
        iPartikkel1GrFmFreq_indx chnget  "iPartikkel1GrFmFreq"
        kPartikkel1GrFmFreq table iPartikkel1GrFmFreq_indx, giSinglePreset
        chnset kPartikkel1GrFmFreq, "Partikkel1GrFmFreq"
        iPartikkel1GrFmIndex_indx chnget  "iPartikkel1GrFmIndex"
        kPartikkel1GrFmIndex table iPartikkel1GrFmIndex_indx, giSinglePreset
        chnset kPartikkel1GrFmIndex, "Partikkel1GrFmIndex"
        iPartikkel1Distribution_indx chnget  "iPartikkel1Distribution"
        kPartikkel1Distribution table iPartikkel1Distribution_indx, giSinglePreset
        chnset kPartikkel1Distribution, "Partikkel1Distribution"
        iPartikkel1GrainDur_indx chnget  "iPartikkel1GrainDur"
        kPartikkel1GrainDur table iPartikkel1GrainDur_indx, giSinglePreset
        chnset kPartikkel1GrainDur, "Partikkel1GrainDur"
        iPartikkel1Sustain_indx chnget  "iPartikkel1Sustain"
        kPartikkel1Sustain table iPartikkel1Sustain_indx, giSinglePreset
        chnset kPartikkel1Sustain, "Partikkel1Sustain"
        iPartikkel1AdRatio_indx chnget  "iPartikkel1AdRatio"
        kPartikkel1AdRatio table iPartikkel1AdRatio_indx, giSinglePreset
        chnset kPartikkel1AdRatio, "Partikkel1AdRatio"
        iPartikkel1Env2Amt_indx chnget  "iPartikkel1Env2Amt"
        kPartikkel1Env2Amt table iPartikkel1Env2Amt_indx, giSinglePreset
        chnset kPartikkel1Env2Amt, "Partikkel1Env2Amt"
        iPartikkel1GrainPitch_indx chnget  "iPartikkel1GrainPitch"
        kPartikkel1GrainPitch table iPartikkel1GrainPitch_indx, giSinglePreset
        chnset kPartikkel1GrainPitch, "Partikkel1GrainPitch"
        iPartikkel1GrainPitch1_indx chnget  "iPartikkel1GrainPitch1"
        kPartikkel1GrainPitch1 table iPartikkel1GrainPitch1_indx, giSinglePreset
        chnset kPartikkel1GrainPitch1, "Partikkel1GrainPitch1"
        iPartikkel1GrainPitch2_indx chnget  "iPartikkel1GrainPitch2"
        kPartikkel1GrainPitch2 table iPartikkel1GrainPitch2_indx, giSinglePreset
        chnset kPartikkel1GrainPitch2, "Partikkel1GrainPitch2"
        iPartikkel1GrainPitch3_indx chnget  "iPartikkel1GrainPitch3"
        kPartikkel1GrainPitch3 table iPartikkel1GrainPitch3_indx, giSinglePreset
        chnset kPartikkel1GrainPitch3, "Partikkel1GrainPitch3"
        iPartikkel1GrainPitch4_indx chnget  "iPartikkel1GrainPitch4"
        kPartikkel1GrainPitch4 table iPartikkel1GrainPitch4_indx, giSinglePreset
        chnset kPartikkel1GrainPitch4, "Partikkel1GrainPitch4"
        iPartikkel1Sweepshape_indx chnget  "iPartikkel1Sweepshape"
        kPartikkel1Sweepshape table iPartikkel1Sweepshape_indx, giSinglePreset
        chnset kPartikkel1Sweepshape, "Partikkel1Sweepshape"
        iPartikkel1PitchFmFreq_indx chnget  "iPartikkel1PitchFmFreq"
        kPartikkel1PitchFmFreq table iPartikkel1PitchFmFreq_indx, giSinglePreset
        chnset kPartikkel1PitchFmFreq, "Partikkel1PitchFmFreq"
        iPartikkel1PitchFmIndex_indx chnget  "iPartikkel1PitchFmIndex"
        kPartikkel1PitchFmIndex table iPartikkel1PitchFmIndex_indx, giSinglePreset
        chnset kPartikkel1PitchFmIndex, "Partikkel1PitchFmIndex"
        iPartikkel1TrainCps_indx chnget  "iPartikkel1TrainCps"
        kPartikkel1TrainCps table iPartikkel1TrainCps_indx, giSinglePreset
        chnset kPartikkel1TrainCps, "Partikkel1TrainCps"
        iPartikkel1TrainPartials_indx chnget  "iPartikkel1TrainPartials"
        kPartikkel1TrainPartials table iPartikkel1TrainPartials_indx, giSinglePreset
        chnset kPartikkel1TrainPartials, "Partikkel1TrainPartials"
        iPartikkel1TrainChroma_indx chnget  "iPartikkel1TrainChroma"
        kPartikkel1TrainChroma table iPartikkel1TrainChroma_indx, giSinglePreset
        chnset kPartikkel1TrainChroma, "Partikkel1TrainChroma"
        iPartikkel1RandomMask_indx chnget  "iPartikkel1RandomMask"
        kPartikkel1RandomMask table iPartikkel1RandomMask_indx, giSinglePreset
        chnset kPartikkel1RandomMask, "Partikkel1RandomMask"
        iPartikkel1WaveX_indx chnget  "iPartikkel1WaveX"
        kPartikkel1WaveX table iPartikkel1WaveX_indx, giSinglePreset
        chnset kPartikkel1WaveX, "Partikkel1WaveX"
        iPartikkel1WaveY_indx chnget  "iPartikkel1WaveY"
        kPartikkel1WaveY table iPartikkel1WaveY_indx, giSinglePreset
        chnset kPartikkel1WaveY, "Partikkel1WaveY"
        iPartikkel1TrainAmp_indx chnget  "iPartikkel1TrainAmp"
        kPartikkel1TrainAmp table iPartikkel1TrainAmp_indx, giSinglePreset
        chnset kPartikkel1TrainAmp, "Partikkel1TrainAmp"
        iLiveFeedbackAmount_indx chnget  "iLiveFeedbackAmount"
        kLiveFeedbackAmount table iLiveFeedbackAmount_indx, giSinglePreset
        chnset kLiveFeedbackAmount, "LiveFeedbackAmount"
        iDryStereoWidth_indx chnget  "iDryStereoWidth"
        kDryStereoWidth table iDryStereoWidth_indx, giSinglePreset
        chnset kDryStereoWidth, "DryStereoWidth"
        iBandpass1RmFreq_indx chnget  "iBandpass1RmFreq"
        kBandpass1RmFreq table iBandpass1RmFreq_indx, giSinglePreset
        chnset kBandpass1RmFreq, "Bandpass1RmFreq"
        iBandpass1RmMix_indx chnget  "iBandpass1RmMix"
        kBandpass1RmMix table iBandpass1RmMix_indx, giSinglePreset
        chnset kBandpass1RmMix, "Bandpass1RmMix"
        iBandpass1Freq_indx chnget  "iBandpass1Freq"
        kBandpass1Freq table iBandpass1Freq_indx, giSinglePreset
        chnset kBandpass1Freq, "Bandpass1Freq"
        iBandpass1BW_indx chnget  "iBandpass1BW"
        kBandpass1BW table iBandpass1BW_indx, giSinglePreset
        chnset kBandpass1BW, "Bandpass1BW"
        iBandpass1Pan_indx chnget  "iBandpass1Pan"
        kBandpass1Pan table iBandpass1Pan_indx, giSinglePreset
        chnset kBandpass1Pan, "Bandpass1Pan"
        iBandpass1Amp_indx chnget  "iBandpass1Amp"
        kBandpass1Amp table iBandpass1Amp_indx, giSinglePreset
        chnset kBandpass1Amp, "Bandpass1Amp"
        iBandpass1Mix_indx chnget  "iBandpass1Mix"
        kBandpass1Mix table iBandpass1Mix_indx, giSinglePreset
        chnset kBandpass1Mix, "Bandpass1Mix"
        iBandpass1_Send_Bandpass2_indx chnget  "iBandpass1_Send_Bandpass2"
        kBandpass1_Send_Bandpass2 table iBandpass1_Send_Bandpass2_indx, giSinglePreset
        chnset kBandpass1_Send_Bandpass2, "Bandpass1_Send_Bandpass2"
        iBandpass1_Send_Lowpass_indx chnget  "iBandpass1_Send_Lowpass"
        kBandpass1_Send_Lowpass table iBandpass1_Send_Lowpass_indx, giSinglePreset
        chnset kBandpass1_Send_Lowpass, "Bandpass1_Send_Lowpass"
        iBandpass1_Send_Bandpass3_indx chnget  "iBandpass1_Send_Bandpass3"
        kBandpass1_Send_Bandpass3 table iBandpass1_Send_Bandpass3_indx, giSinglePreset
        chnset kBandpass1_Send_Bandpass3, "Bandpass1_Send_Bandpass3"
        iBandpass1_Send_DlyL_indx chnget  "iBandpass1_Send_DlyL"
        kBandpass1_Send_DlyL table iBandpass1_Send_DlyL_indx, giSinglePreset
        chnset kBandpass1_Send_DlyL, "Bandpass1_Send_DlyL"
        iBandpass1_Send_DlyR_indx chnget  "iBandpass1_Send_DlyR"
        kBandpass1_Send_DlyR table iBandpass1_Send_DlyR_indx, giSinglePreset
        chnset kBandpass1_Send_DlyR, "Bandpass1_Send_DlyR"
        iBandpass2Freq_indx chnget  "iBandpass2Freq"
        kBandpass2Freq table iBandpass2Freq_indx, giSinglePreset
        chnset kBandpass2Freq, "Bandpass2Freq"
        iBandpass2BW_indx chnget  "iBandpass2BW"
        kBandpass2BW table iBandpass2BW_indx, giSinglePreset
        chnset kBandpass2BW, "Bandpass2BW"
        iBandpass2Pan_indx chnget  "iBandpass2Pan"
        kBandpass2Pan table iBandpass2Pan_indx, giSinglePreset
        chnset kBandpass2Pan, "Bandpass2Pan"
        iBandpass2Amp_indx chnget  "iBandpass2Amp"
        kBandpass2Amp table iBandpass2Amp_indx, giSinglePreset
        chnset kBandpass2Amp, "Bandpass2Amp"
        iBandpass2Mix_indx chnget  "iBandpass2Mix"
        kBandpass2Mix table iBandpass2Mix_indx, giSinglePreset
        chnset kBandpass2Mix, "Bandpass2Mix"
        iBandpass2_Send_Lowpass_indx chnget  "iBandpass2_Send_Lowpass"
        kBandpass2_Send_Lowpass table iBandpass2_Send_Lowpass_indx, giSinglePreset
        chnset kBandpass2_Send_Lowpass, "Bandpass2_Send_Lowpass"
        iBandpass2_Send_Bandpass3_indx chnget  "iBandpass2_Send_Bandpass3"
        kBandpass2_Send_Bandpass3 table iBandpass2_Send_Bandpass3_indx, giSinglePreset
        chnset kBandpass2_Send_Bandpass3, "Bandpass2_Send_Bandpass3"
        iBandpass2_Send_DlyL_indx chnget  "iBandpass2_Send_DlyL"
        kBandpass2_Send_DlyL table iBandpass2_Send_DlyL_indx, giSinglePreset
        chnset kBandpass2_Send_DlyL, "Bandpass2_Send_DlyL"
        iBandpass2_Send_DlyR_indx chnget  "iBandpass2_Send_DlyR"
        kBandpass2_Send_DlyR table iBandpass2_Send_DlyR_indx, giSinglePreset
        chnset kBandpass2_Send_DlyR, "Bandpass2_Send_DlyR"
        iLowpassFreq_indx chnget  "iLowpassFreq"
        kLowpassFreq table iLowpassFreq_indx, giSinglePreset
        chnset kLowpassFreq, "LowpassFreq"
        iLowpassRes_indx chnget  "iLowpassRes"
        kLowpassRes table iLowpassRes_indx, giSinglePreset
        chnset kLowpassRes, "LowpassRes"
        iLowpassDist_indx chnget  "iLowpassDist"
        kLowpassDist table iLowpassDist_indx, giSinglePreset
        chnset kLowpassDist, "LowpassDist"
        iLowpassPan_indx chnget  "iLowpassPan"
        kLowpassPan table iLowpassPan_indx, giSinglePreset
        chnset kLowpassPan, "LowpassPan"
        iLowpassAmp_indx chnget  "iLowpassAmp"
        kLowpassAmp table iLowpassAmp_indx, giSinglePreset
        chnset kLowpassAmp, "LowpassAmp"
        iLowpassMix_indx chnget  "iLowpassMix"
        kLowpassMix table iLowpassMix_indx, giSinglePreset
        chnset kLowpassMix, "LowpassMix"
        iLowpass_Send_BP3_indx chnget  "iLowpass_Send_BP3"
        kLowpass_Send_BP3 table iLowpass_Send_BP3_indx, giSinglePreset
        chnset kLowpass_Send_BP3, "Lowpass_Send_BP3"
        iLowpass_Send_DlyL_indx chnget  "iLowpass_Send_DlyL"
        kLowpass_Send_DlyL table iLowpass_Send_DlyL_indx, giSinglePreset
        chnset kLowpass_Send_DlyL, "Lowpass_Send_DlyL"
        iLowpass_Send_DlyR_indx chnget  "iLowpass_Send_DlyR"
        kLowpass_Send_DlyR table iLowpass_Send_DlyR_indx, giSinglePreset
        chnset kLowpass_Send_DlyR, "Lowpass_Send_DlyR"
        iBandpass3Freq_indx chnget  "iBandpass3Freq"
        kBandpass3Freq table iBandpass3Freq_indx, giSinglePreset
        chnset kBandpass3Freq, "Bandpass3Freq"
        iBandpass3BW_indx chnget  "iBandpass3BW"
        kBandpass3BW table iBandpass3BW_indx, giSinglePreset
        chnset kBandpass3BW, "Bandpass3BW"
        iBandpass3Pan_indx chnget  "iBandpass3Pan"
        kBandpass3Pan table iBandpass3Pan_indx, giSinglePreset
        chnset kBandpass3Pan, "Bandpass3Pan"
        iBandpass3Amp_indx chnget  "iBandpass3Amp"
        kBandpass3Amp table iBandpass3Amp_indx, giSinglePreset
        chnset kBandpass3Amp, "Bandpass3Amp"
        iBandpass3Mix_indx chnget  "iBandpass3Mix"
        kBandpass3Mix table iBandpass3Mix_indx, giSinglePreset
        chnset kBandpass3Mix, "Bandpass3Mix"
        iBandpass3_Send_DlyL_indx chnget  "iBandpass3_Send_DlyL"
        kBandpass3_Send_DlyL table iBandpass3_Send_DlyL_indx, giSinglePreset
        chnset kBandpass3_Send_DlyL, "Bandpass3_Send_DlyL"
        iBandpass3_Send_DlyR_indx chnget  "iBandpass3_Send_DlyR"
        kBandpass3_Send_DlyR table iBandpass3_Send_DlyR_indx, giSinglePreset
        chnset kBandpass3_Send_DlyR, "Bandpass3_Send_DlyR"
        iDelayTimeLeft_indx chnget  "iDelayTimeLeft"
        kDelayTimeLeft table iDelayTimeLeft_indx, giSinglePreset
        chnset kDelayTimeLeft, "DelayTimeLeft"
        iDelayTimeRight_indx chnget  "iDelayTimeRight"
        kDelayTimeRight table iDelayTimeRight_indx, giSinglePreset
        chnset kDelayTimeRight, "DelayTimeRight"
        iDelayFeedbackLeft_indx chnget  "iDelayFeedbackLeft"
        kDelayFeedbackLeft table iDelayFeedbackLeft_indx, giSinglePreset
        chnset kDelayFeedbackLeft, "DelayFeedbackLeft"
        iDelayFeedbackRight_indx chnget  "iDelayFeedbackRight"
        kDelayFeedbackRight table iDelayFeedbackRight_indx, giSinglePreset
        chnset kDelayFeedbackRight, "DelayFeedbackRight"
        iDelayXFeedback_indx chnget  "iDelayXFeedback"
        kDelayXFeedback table iDelayXFeedback_indx, giSinglePreset
        chnset kDelayXFeedback, "DelayXFeedback"
        iDelayHpFreq_indx chnget  "iDelayHpFreq"
        kDelayHpFreq table iDelayHpFreq_indx, giSinglePreset
        chnset kDelayHpFreq, "DelayHpFreq"
        iDelayLpFreq_indx chnget  "iDelayLpFreq"
        kDelayLpFreq table iDelayLpFreq_indx, giSinglePreset
        chnset kDelayLpFreq, "DelayLpFreq"
        iDelayStereoWidth_indx chnget  "iDelayStereoWidth"
        kDelayStereoWidth table iDelayStereoWidth_indx, giSinglePreset
        chnset kDelayStereoWidth, "DelayStereoWidth"
        iDelayAmp_indx chnget  "iDelayAmp"
        kDelayAmp table iDelayAmp_indx, giSinglePreset
        chnset kDelayAmp, "DelayAmp"
        iDelayMix_indx chnget  "iDelayMix"
        kDelayMix table iDelayMix_indx, giSinglePreset
        chnset kDelayMix, "DelayMix"
        iLFO1_Amp_indx chnget  "iLFO1_Amp"
        kLFO1_Amp table iLFO1_Amp_indx, giSinglePreset
        chnset kLFO1_Amp, "LFO1_Amp"
        iLFO1_Freq_indx chnget  "iLFO1_Freq"
        kLFO1_Freq table iLFO1_Freq_indx, giSinglePreset
        chnset kLFO1_Freq, "LFO1_Freq"
        iLFO1_Waveform_indx chnget  "iLFO1_Waveform"
        kLFO1_Waveform table iLFO1_Waveform_indx, giSinglePreset
        chnset kLFO1_Waveform, "LFO1_Waveform"
        iLFO1_Phase_indx chnget  "iLFO1_Phase"
        kLFO1_Phase table iLFO1_Phase_indx, giSinglePreset
        chnset kLFO1_Phase, "LFO1_Phase"
        iLFO1_Global_indx chnget  "iLFO1_Global"
        kLFO1_Global table iLFO1_Global_indx, giSinglePreset
        chnset kLFO1_Global, "LFO1_Global"
        iLFO2_Amp_indx chnget  "iLFO2_Amp"
        kLFO2_Amp table iLFO2_Amp_indx, giSinglePreset
        chnset kLFO2_Amp, "LFO2_Amp"
        iLFO2_Freq_indx chnget  "iLFO2_Freq"
        kLFO2_Freq table iLFO2_Freq_indx, giSinglePreset
        chnset kLFO2_Freq, "LFO2_Freq"
        iLFO2_Waveform_indx chnget  "iLFO2_Waveform"
        kLFO2_Waveform table iLFO2_Waveform_indx, giSinglePreset
        chnset kLFO2_Waveform, "LFO2_Waveform"
        iLFO2_Phase_indx chnget  "iLFO2_Phase"
        kLFO2_Phase table iLFO2_Phase_indx, giSinglePreset
        chnset kLFO2_Phase, "LFO2_Phase"
        iLFO2_Global_indx chnget  "iLFO2_Global"
        kLFO2_Global table iLFO2_Global_indx, giSinglePreset
        chnset kLFO2_Global, "LFO2_Global"
        iLFO3_Amp_indx chnget  "iLFO3_Amp"
        kLFO3_Amp table iLFO3_Amp_indx, giSinglePreset
        chnset kLFO3_Amp, "LFO3_Amp"
        iLFO3_Freq_indx chnget  "iLFO3_Freq"
        kLFO3_Freq table iLFO3_Freq_indx, giSinglePreset
        chnset kLFO3_Freq, "LFO3_Freq"
        iLFO3_Waveform_indx chnget  "iLFO3_Waveform"
        kLFO3_Waveform table iLFO3_Waveform_indx, giSinglePreset
        chnset kLFO3_Waveform, "LFO3_Waveform"
        iLFO3_Phase_indx chnget  "iLFO3_Phase"
        kLFO3_Phase table iLFO3_Phase_indx, giSinglePreset
        chnset kLFO3_Phase, "LFO3_Phase"
        iLFO3_Global_indx chnget  "iLFO3_Global"
        kLFO3_Global table iLFO3_Global_indx, giSinglePreset
        chnset kLFO3_Global, "LFO3_Global"
        iLFO4_Amp_indx chnget  "iLFO4_Amp"
        kLFO4_Amp table iLFO4_Amp_indx, giSinglePreset
        chnset kLFO4_Amp, "LFO4_Amp"
        iLFO4_Freq_indx chnget  "iLFO4_Freq"
        kLFO4_Freq table iLFO4_Freq_indx, giSinglePreset
        chnset kLFO4_Freq, "LFO4_Freq"
        iLFO4_Waveform_indx chnget  "iLFO4_Waveform"
        kLFO4_Waveform table iLFO4_Waveform_indx, giSinglePreset
        chnset kLFO4_Waveform, "LFO4_Waveform"
        iLFO4_Phase_indx chnget  "iLFO4_Phase"
        kLFO4_Phase table iLFO4_Phase_indx, giSinglePreset
        chnset kLFO4_Phase, "LFO4_Phase"
        iLFO4_Global_indx chnget  "iLFO4_Global"
        kLFO4_Global table iLFO4_Global_indx, giSinglePreset
        chnset kLFO4_Global, "LFO4_Global"
        iEnvelope1_Amp_indx chnget  "iEnvelope1_Amp"
        kEnvelope1_Amp table iEnvelope1_Amp_indx, giSinglePreset
        chnset kEnvelope1_Amp, "Envelope1_Amp"
        iEnvelope1_Delay_indx chnget  "iEnvelope1_Delay"
        kEnvelope1_Delay table iEnvelope1_Delay_indx, giSinglePreset
        chnset kEnvelope1_Delay, "Envelope1_Delay"
        iEnvelope1_Attack_indx chnget  "iEnvelope1_Attack"
        kEnvelope1_Attack table iEnvelope1_Attack_indx, giSinglePreset
        chnset kEnvelope1_Attack, "Envelope1_Attack"
        iEnvelope1_Decay_indx chnget  "iEnvelope1_Decay"
        kEnvelope1_Decay table iEnvelope1_Decay_indx, giSinglePreset
        chnset kEnvelope1_Decay, "Envelope1_Decay"
        iEnvelope1_Sustain_indx chnget  "iEnvelope1_Sustain"
        kEnvelope1_Sustain table iEnvelope1_Sustain_indx, giSinglePreset
        chnset kEnvelope1_Sustain, "Envelope1_Sustain"
        iEnvelope1_Release_indx chnget  "iEnvelope1_Release"
        kEnvelope1_Release table iEnvelope1_Release_indx, giSinglePreset
        chnset kEnvelope1_Release, "Envelope1_Release"
        iEnvelope1_Curve_indx chnget  "iEnvelope1_Curve"
        kEnvelope1_Curve table iEnvelope1_Curve_indx, giSinglePreset
        chnset kEnvelope1_Curve, "Envelope1_Curve"
        iEnvelope1_Retrig_indx chnget  "iEnvelope1_Retrig"
        kEnvelope1_Retrig table iEnvelope1_Retrig_indx, giSinglePreset
        chnset kEnvelope1_Retrig, "Envelope1_Retrig"
        iEnvelope2_Amp_indx chnget  "iEnvelope2_Amp"
        kEnvelope2_Amp table iEnvelope2_Amp_indx, giSinglePreset
        chnset kEnvelope2_Amp, "Envelope2_Amp"
        iEnvelope2_Delay_indx chnget  "iEnvelope2_Delay"
        kEnvelope2_Delay table iEnvelope2_Delay_indx, giSinglePreset
        chnset kEnvelope2_Delay, "Envelope2_Delay"
        iEnvelope2_Attack_indx chnget  "iEnvelope2_Attack"
        kEnvelope2_Attack table iEnvelope2_Attack_indx, giSinglePreset
        chnset kEnvelope2_Attack, "Envelope2_Attack"
        iEnvelope2_Decay_indx chnget  "iEnvelope2_Decay"
        kEnvelope2_Decay table iEnvelope2_Decay_indx, giSinglePreset
        chnset kEnvelope2_Decay, "Envelope2_Decay"
        iEnvelope2_Sustain_indx chnget  "iEnvelope2_Sustain"
        kEnvelope2_Sustain table iEnvelope2_Sustain_indx, giSinglePreset
        chnset kEnvelope2_Sustain, "Envelope2_Sustain"
        iEnvelope2_Release_indx chnget  "iEnvelope2_Release"
        kEnvelope2_Release table iEnvelope2_Release_indx, giSinglePreset
        chnset kEnvelope2_Release, "Envelope2_Release"
        iEnvelope2_Curve_indx chnget  "iEnvelope2_Curve"
        kEnvelope2_Curve table iEnvelope2_Curve_indx, giSinglePreset
        chnset kEnvelope2_Curve, "Envelope2_Curve"
        iEnvelope2_Retrig_indx chnget  "iEnvelope2_Retrig"
        kEnvelope2_Retrig table iEnvelope2_Retrig_indx, giSinglePreset
        chnset kEnvelope2_Retrig, "Envelope2_Retrig"
        iEnvelope3_Amp_indx chnget  "iEnvelope3_Amp"
        kEnvelope3_Amp table iEnvelope3_Amp_indx, giSinglePreset
        chnset kEnvelope3_Amp, "Envelope3_Amp"
        iEnvelope3_Delay_indx chnget  "iEnvelope3_Delay"
        kEnvelope3_Delay table iEnvelope3_Delay_indx, giSinglePreset
        chnset kEnvelope3_Delay, "Envelope3_Delay"
        iEnvelope3_Attack_indx chnget  "iEnvelope3_Attack"
        kEnvelope3_Attack table iEnvelope3_Attack_indx, giSinglePreset
        chnset kEnvelope3_Attack, "Envelope3_Attack"
        iEnvelope3_Decay_indx chnget  "iEnvelope3_Decay"
        kEnvelope3_Decay table iEnvelope3_Decay_indx, giSinglePreset
        chnset kEnvelope3_Decay, "Envelope3_Decay"
        iEnvelope3_Sustain_indx chnget  "iEnvelope3_Sustain"
        kEnvelope3_Sustain table iEnvelope3_Sustain_indx, giSinglePreset
        chnset kEnvelope3_Sustain, "Envelope3_Sustain"
        iEnvelope3_Release_indx chnget  "iEnvelope3_Release"
        kEnvelope3_Release table iEnvelope3_Release_indx, giSinglePreset
        chnset kEnvelope3_Release, "Envelope3_Release"
        iEnvelope3_Curve_indx chnget  "iEnvelope3_Curve"
        kEnvelope3_Curve table iEnvelope3_Curve_indx, giSinglePreset
        chnset kEnvelope3_Curve, "Envelope3_Curve"
        iEnvelope3_Retrig_indx chnget  "iEnvelope3_Retrig"
        kEnvelope3_Retrig table iEnvelope3_Retrig_indx, giSinglePreset
        chnset kEnvelope3_Retrig, "Envelope3_Retrig"
        iEnvelope4_Amp_indx chnget  "iEnvelope4_Amp"
        kEnvelope4_Amp table iEnvelope4_Amp_indx, giSinglePreset
        chnset kEnvelope4_Amp, "Envelope4_Amp"
        iEnvelope4_Delay_indx chnget  "iEnvelope4_Delay"
        kEnvelope4_Delay table iEnvelope4_Delay_indx, giSinglePreset
        chnset kEnvelope4_Delay, "Envelope4_Delay"
        iEnvelope4_Attack_indx chnget  "iEnvelope4_Attack"
        kEnvelope4_Attack table iEnvelope4_Attack_indx, giSinglePreset
        chnset kEnvelope4_Attack, "Envelope4_Attack"
        iEnvelope4_Decay_indx chnget  "iEnvelope4_Decay"
        kEnvelope4_Decay table iEnvelope4_Decay_indx, giSinglePreset
        chnset kEnvelope4_Decay, "Envelope4_Decay"
        iEnvelope4_Sustain_indx chnget  "iEnvelope4_Sustain"
        kEnvelope4_Sustain table iEnvelope4_Sustain_indx, giSinglePreset
        chnset kEnvelope4_Sustain, "Envelope4_Sustain"
        iEnvelope4_Release_indx chnget  "iEnvelope4_Release"
        kEnvelope4_Release table iEnvelope4_Release_indx, giSinglePreset
        chnset kEnvelope4_Release, "Envelope4_Release"
        iEnvelope4_Curve_indx chnget  "iEnvelope4_Curve"
        kEnvelope4_Curve table iEnvelope4_Curve_indx, giSinglePreset
        chnset kEnvelope4_Curve, "Envelope4_Curve"
        iEnvelope4_Retrig_indx chnget  "iEnvelope4_Retrig"
        kEnvelope4_Retrig table iEnvelope4_Retrig_indx, giSinglePreset
        chnset kEnvelope4_Retrig, "Envelope4_Retrig"
        iRandh1_Amp_indx chnget  "iRandh1_Amp"
        kRandh1_Amp table iRandh1_Amp_indx, giSinglePreset
        chnset kRandh1_Amp, "Randh1_Amp"
        iRandh1_Freq_indx chnget  "iRandh1_Freq"
        kRandh1_Freq table iRandh1_Freq_indx, giSinglePreset
        chnset kRandh1_Freq, "Randh1_Freq"
        iRandh1_Retrig_indx chnget  "iRandh1_Retrig"
        kRandh1_Retrig table iRandh1_Retrig_indx, giSinglePreset
        chnset kRandh1_Retrig, "Randh1_Retrig"
        iRandh2_Amp_indx chnget  "iRandh2_Amp"
        kRandh2_Amp table iRandh2_Amp_indx, giSinglePreset
        chnset kRandh2_Amp, "Randh2_Amp"
        iRandh2_Freq_indx chnget  "iRandh2_Freq"
        kRandh2_Freq table iRandh2_Freq_indx, giSinglePreset
        chnset kRandh2_Freq, "Randh2_Freq"
        iRandh2_Retrig_indx chnget  "iRandh2_Retrig"
        kRandh2_Retrig table iRandh2_Retrig_indx, giSinglePreset
        chnset kRandh2_Retrig, "Randh2_Retrig"
        iRspline1_Amp_indx chnget  "iRspline1_Amp"
        kRspline1_Amp table iRspline1_Amp_indx, giSinglePreset
        chnset kRspline1_Amp, "Rspline1_Amp"
        iRspline1_MinFreq_indx chnget  "iRspline1_MinFreq"
        kRspline1_MinFreq table iRspline1_MinFreq_indx, giSinglePreset
        chnset kRspline1_MinFreq, "Rspline1_MinFreq"
        iRspline1_MaxFreq_indx chnget  "iRspline1_MaxFreq"
        kRspline1_MaxFreq table iRspline1_MaxFreq_indx, giSinglePreset
        chnset kRspline1_MaxFreq, "Rspline1_MaxFreq"
        iRspline2_Amp_indx chnget  "iRspline2_Amp"
        kRspline2_Amp table iRspline2_Amp_indx, giSinglePreset
        chnset kRspline2_Amp, "Rspline2_Amp"
        iRspline2_MinFreq_indx chnget  "iRspline2_MinFreq"
        kRspline2_MinFreq table iRspline2_MinFreq_indx, giSinglePreset
        chnset kRspline2_MinFreq, "Rspline2_MinFreq"
        iRspline2_MaxFreq_indx chnget  "iRspline2_MaxFreq"
        kRspline2_MaxFreq table iRspline2_MaxFreq_indx, giSinglePreset
        chnset kRspline2_MaxFreq, "Rspline2_MaxFreq"
        iDivider1Input_indx chnget  "iDivider1Input"
        kDivider1Input table iDivider1Input_indx, giSinglePreset
        chnset kDivider1Input, "Divider1Input"
        iDivider2Input_indx chnget  "iDivider2Input"
        kDivider2Input table iDivider2Input_indx, giSinglePreset
        chnset kDivider2Input, "Divider2Input"
        iDivider3Input_indx chnget  "iDivider3Input"
        kDivider3Input table iDivider3Input_indx, giSinglePreset
        chnset kDivider3Input, "Divider3Input"
        iDivider4Input_indx chnget  "iDivider4Input"
        kDivider4Input table iDivider4Input_indx, giSinglePreset
        chnset kDivider4Input, "Divider4Input"
        iModulo1Input_indx chnget  "iModulo1Input"
        kModulo1Input table iModulo1Input_indx, giSinglePreset
        chnset kModulo1Input, "Modulo1Input"
        iModulo1Value_indx chnget  "iModulo1Value"
        kModulo1Value table iModulo1Value_indx, giSinglePreset
        chnset kModulo1Value, "Modulo1Value"
        iMultiplier1Input1_indx chnget  "iMultiplier1Input1"
        kMultiplier1Input1 table iMultiplier1Input1_indx, giSinglePreset
        chnset kMultiplier1Input1, "Multiplier1Input1"
        iMultiplier1Input2_indx chnget  "iMultiplier1Input2"
        kMultiplier1Input2 table iMultiplier1Input2_indx, giSinglePreset
        chnset kMultiplier1Input2, "Multiplier1Input2"
        iMultiplier2Input1_indx chnget  "iMultiplier2Input1"
        kMultiplier2Input1 table iMultiplier2Input1_indx, giSinglePreset
        chnset kMultiplier2Input1, "Multiplier2Input1"
        iMultiplier2Input2_indx chnget  "iMultiplier2Input2"
        kMultiplier2Input2 table iMultiplier2Input2_indx, giSinglePreset
        chnset kMultiplier2Input2, "Multiplier2Input2"
        iFunc1Input_indx chnget  "iFunc1Input"
        kFunc1Input table iFunc1Input_indx, giSinglePreset
        chnset kFunc1Input, "Func1Input"
        iFunc2Input_indx chnget  "iFunc2Input"
        kFunc2Input table iFunc2Input_indx, giSinglePreset
        chnset kFunc2Input, "Func2Input"
        iFunc3Input_indx chnget  "iFunc3Input"
        kFunc3Input table iFunc3Input_indx, giSinglePreset
        chnset kFunc3Input, "Func3Input"
        iFunc4Input_indx chnget  "iFunc4Input"
        kFunc4Input table iFunc4Input_indx, giSinglePreset
        chnset kFunc4Input, "Func4Input"
        iTransientAttack1_indx chnget  "iTransientAttack1"
        kTransientAttack1 table iTransientAttack1_indx, giSinglePreset
        chnset kTransientAttack1, "TransientAttack1"
        iTransientRelease1_indx chnget  "iTransientRelease1"
        kTransientRelease1 table iTransientRelease1_indx, giSinglePreset
        chnset kTransientRelease1, "TransientRelease1"
        iTransientAttack2_indx chnget  "iTransientAttack2"
        kTransientAttack2 table iTransientAttack2_indx, giSinglePreset
        chnset kTransientAttack2, "TransientAttack2"
        iTransientRelease2_indx chnget  "iTransientRelease2"
        kTransientRelease2 table iTransientRelease2_indx, giSinglePreset
        chnset kTransientRelease2, "TransientRelease2"
        iTransientAttack3_indx chnget  "iTransientAttack3"
        kTransientAttack3 table iTransientAttack3_indx, giSinglePreset
        chnset kTransientAttack3, "TransientAttack3"
        iTransientRelease3_indx chnget  "iTransientRelease3"
        kTransientRelease3 table iTransientRelease3_indx, giSinglePreset
        chnset kTransientRelease3, "TransientRelease3"
        iTransientAttack4_indx chnget  "iTransientAttack4"
        kTransientAttack4 table iTransientAttack4_indx, giSinglePreset
        chnset kTransientAttack4, "TransientAttack4"
        iTransientRelease4_indx chnget  "iTransientRelease4"
        kTransientRelease4 table iTransientRelease4_indx, giSinglePreset
        chnset kTransientRelease4, "TransientRelease4"
        iPortamento_Allnotes_indx chnget  "iPortamento_Allnotes"
        kPortamento_Allnotes table iPortamento_Allnotes_indx, giSinglePreset
        chnset kPortamento_Allnotes, "Portamento_Allnotes"
        iPortamentoCps_indx chnget  "iPortamentoCps"
        kPortamentoCps table iPortamentoCps_indx, giSinglePreset
        chnset kPortamentoCps, "PortamentoCps"
        iPortamentoNote_indx chnget  "iPortamentoNote"
        kPortamentoNote table iPortamentoNote_indx, giSinglePreset
        chnset kPortamentoNote, "PortamentoNote"
        iPortamentoInterval_indx chnget  "iPortamentoInterval"
        kPortamentoInterval table iPortamentoInterval_indx, giSinglePreset
        chnset kPortamentoInterval, "PortamentoInterval"
        iMidiNoteOffset_indx chnget  "iMidiNoteOffset"
        kMidiNoteOffset table iMidiNoteOffset_indx, giSinglePreset
        chnset kMidiNoteOffset, "MidiNoteOffset"
        iAnalysisTimeOffset_indx chnget  "iAnalysisTimeOffset"
        kAnalysisTimeOffset table iAnalysisTimeOffset_indx, giSinglePreset
        chnset kAnalysisTimeOffset, "AnalysisTimeOffset"
        igainmasks1Morf_indx chnget  "igainmasks1Morf"
        kgainmasks1Morf table igainmasks1Morf_indx, giSinglePreset
        chnset kgainmasks1Morf, "gainmasks1Morf"
        ichannelmasks1Morf_indx chnget  "ichannelmasks1Morf"
        kchannelmasks1Morf table ichannelmasks1Morf_indx, giSinglePreset
        chnset kchannelmasks1Morf, "channelmasks1Morf"
        iwavemasks1Morf_indx chnget  "iwavemasks1Morf"
        kwavemasks1Morf table iwavemasks1Morf_indx, giSinglePreset
        chnset kwavemasks1Morf, "wavemasks1Morf"
        ifreqstartmasks1Morf_indx chnget  "ifreqstartmasks1Morf"
        kfreqstartmasks1Morf table ifreqstartmasks1Morf_indx, giSinglePreset
        chnset kfreqstartmasks1Morf, "freqstartmasks1Morf"
        ifreqendmasks1Morf_indx chnget  "ifreqendmasks1Morf"
        kfreqendmasks1Morf table ifreqendmasks1Morf_indx, giSinglePreset
        chnset kfreqendmasks1Morf, "freqendmasks1Morf"
        ifmampmasks1Morf_indx chnget  "ifmampmasks1Morf"
        kfmampmasks1Morf table ifmampmasks1Morf_indx, giSinglePreset
        chnset kfmampmasks1Morf, "fmampmasks1Morf"
        iPartikkel1GrainRateBpmSync_indx chnget  "iPartikkel1GrainRateBpmSync"
        kPartikkel1GrainRateBpmSync table iPartikkel1GrainRateBpmSync_indx, giSinglePreset
        chnset kPartikkel1GrainRateBpmSync, "Partikkel1GrainRateBpmSync"
        iPartikkel1GrFmFreqBpmSync_indx chnget  "iPartikkel1GrFmFreqBpmSync"
        kPartikkel1GrFmFreqBpmSync table iPartikkel1GrFmFreqBpmSync_indx, giSinglePreset
        chnset kPartikkel1GrFmFreqBpmSync, "Partikkel1GrFmFreqBpmSync"
        iPartikkel1PitchFmFreqBpmSync_indx chnget  "iPartikkel1PitchFmFreqBpmSync"
        kPartikkel1PitchFmFreqBpmSync table iPartikkel1PitchFmFreqBpmSync_indx, giSinglePreset
        chnset kPartikkel1PitchFmFreqBpmSync, "Partikkel1PitchFmFreqBpmSync"
        iPartikkel1GrainDelayTime1BpmSync_indx chnget  "iPartikkel1GrainDelayTime1BpmSync"
        kPartikkel1GrainDelayTime1BpmSync table iPartikkel1GrainDelayTime1BpmSync_indx, giSinglePreset
        chnset kPartikkel1GrainDelayTime1BpmSync, "Partikkel1GrainDelayTime1BpmSync"
        iPartikkel1GrainDelayTime2BpmSync_indx chnget  "iPartikkel1GrainDelayTime2BpmSync"
        kPartikkel1GrainDelayTime2BpmSync table iPartikkel1GrainDelayTime2BpmSync_indx, giSinglePreset
        chnset kPartikkel1GrainDelayTime2BpmSync, "Partikkel1GrainDelayTime2BpmSync"
        iPartikkel1GrainDelayTime3BpmSync_indx chnget  "iPartikkel1GrainDelayTime3BpmSync"
        kPartikkel1GrainDelayTime3BpmSync table iPartikkel1GrainDelayTime3BpmSync_indx, giSinglePreset
        chnset kPartikkel1GrainDelayTime3BpmSync, "Partikkel1GrainDelayTime3BpmSync"
        iPartikkel1GrainDelayTime4BpmSync_indx chnget  "iPartikkel1GrainDelayTime4BpmSync"
        kPartikkel1GrainDelayTime4BpmSync table iPartikkel1GrainDelayTime4BpmSync_indx, giSinglePreset
        chnset kPartikkel1GrainDelayTime4BpmSync, "Partikkel1GrainDelayTime4BpmSync"
        iBandpass1RmFreqBpmSync_indx chnget  "iBandpass1RmFreqBpmSync"
        kBandpass1RmFreqBpmSync table iBandpass1RmFreqBpmSync_indx, giSinglePreset
        chnset kBandpass1RmFreqBpmSync, "Bandpass1RmFreqBpmSync"
        iDelayTimeBpmSync_indx chnget  "iDelayTimeBpmSync"
        kDelayTimeBpmSync table iDelayTimeBpmSync_indx, giSinglePreset
        chnset kDelayTimeBpmSync, "DelayTimeBpmSync"
        iLFO1_FreqBpmSync_indx chnget  "iLFO1_FreqBpmSync"
        kLFO1_FreqBpmSync table iLFO1_FreqBpmSync_indx, giSinglePreset
        chnset kLFO1_FreqBpmSync, "LFO1_FreqBpmSync"
        iLFO2_FreqBpmSync_indx chnget  "iLFO2_FreqBpmSync"
        kLFO2_FreqBpmSync table iLFO2_FreqBpmSync_indx, giSinglePreset
        chnset kLFO2_FreqBpmSync, "LFO2_FreqBpmSync"
        iLFO3_FreqBpmSync_indx chnget  "iLFO3_FreqBpmSync"
        kLFO3_FreqBpmSync table iLFO3_FreqBpmSync_indx, giSinglePreset
        chnset kLFO3_FreqBpmSync, "LFO3_FreqBpmSync"
        iLFO4_FreqBpmSync_indx chnget  "iLFO4_FreqBpmSync"
        kLFO4_FreqBpmSync table iLFO4_FreqBpmSync_indx, giSinglePreset
        chnset kLFO4_FreqBpmSync, "LFO4_FreqBpmSync"
        iEnvelope1_DelayBpmSync_indx chnget  "iEnvelope1_DelayBpmSync"
        kEnvelope1_DelayBpmSync table iEnvelope1_DelayBpmSync_indx, giSinglePreset
        chnset kEnvelope1_DelayBpmSync, "Envelope1_DelayBpmSync"
        iEnvelope1_AttackBpmSync_indx chnget  "iEnvelope1_AttackBpmSync"
        kEnvelope1_AttackBpmSync table iEnvelope1_AttackBpmSync_indx, giSinglePreset
        chnset kEnvelope1_AttackBpmSync, "Envelope1_AttackBpmSync"
        iEnvelope1_DecayBpmSync_indx chnget  "iEnvelope1_DecayBpmSync"
        kEnvelope1_DecayBpmSync table iEnvelope1_DecayBpmSync_indx, giSinglePreset
        chnset kEnvelope1_DecayBpmSync, "Envelope1_DecayBpmSync"
        iEnvelope1_ReleaseBpmSync_indx chnget  "iEnvelope1_ReleaseBpmSync"
        kEnvelope1_ReleaseBpmSync table iEnvelope1_ReleaseBpmSync_indx, giSinglePreset
        chnset kEnvelope1_ReleaseBpmSync, "Envelope1_ReleaseBpmSync"
        iEnvelope2_DelayBpmSync_indx chnget  "iEnvelope2_DelayBpmSync"
        kEnvelope2_DelayBpmSync table iEnvelope2_DelayBpmSync_indx, giSinglePreset
        chnset kEnvelope2_DelayBpmSync, "Envelope2_DelayBpmSync"
        iEnvelope2_AttackBpmSync_indx chnget  "iEnvelope2_AttackBpmSync"
        kEnvelope2_AttackBpmSync table iEnvelope2_AttackBpmSync_indx, giSinglePreset
        chnset kEnvelope2_AttackBpmSync, "Envelope2_AttackBpmSync"
        iEnvelope2_DecayBpmSync_indx chnget  "iEnvelope2_DecayBpmSync"
        kEnvelope2_DecayBpmSync table iEnvelope2_DecayBpmSync_indx, giSinglePreset
        chnset kEnvelope2_DecayBpmSync, "Envelope2_DecayBpmSync"
        iEnvelope2_ReleaseBpmSync_indx chnget  "iEnvelope2_ReleaseBpmSync"
        kEnvelope2_ReleaseBpmSync table iEnvelope2_ReleaseBpmSync_indx, giSinglePreset
        chnset kEnvelope2_ReleaseBpmSync, "Envelope2_ReleaseBpmSync"
        iEnvelope3_DelayBpmSync_indx chnget  "iEnvelope3_DelayBpmSync"
        kEnvelope3_DelayBpmSync table iEnvelope3_DelayBpmSync_indx, giSinglePreset
        chnset kEnvelope3_DelayBpmSync, "Envelope3_DelayBpmSync"
        iEnvelope3_AttackBpmSync_indx chnget  "iEnvelope3_AttackBpmSync"
        kEnvelope3_AttackBpmSync table iEnvelope3_AttackBpmSync_indx, giSinglePreset
        chnset kEnvelope3_AttackBpmSync, "Envelope3_AttackBpmSync"
        iEnvelope3_DecayBpmSync_indx chnget  "iEnvelope3_DecayBpmSync"
        kEnvelope3_DecayBpmSync table iEnvelope3_DecayBpmSync_indx, giSinglePreset
        chnset kEnvelope3_DecayBpmSync, "Envelope3_DecayBpmSync"
        iEnvelope3_ReleaseBpmSync_indx chnget  "iEnvelope3_ReleaseBpmSync"
        kEnvelope3_ReleaseBpmSync table iEnvelope3_ReleaseBpmSync_indx, giSinglePreset
        chnset kEnvelope3_ReleaseBpmSync, "Envelope3_ReleaseBpmSync"
        iEnvelope4_DelayBpmSync_indx chnget  "iEnvelope4_DelayBpmSync"
        kEnvelope4_DelayBpmSync table iEnvelope4_DelayBpmSync_indx, giSinglePreset
        chnset kEnvelope4_DelayBpmSync, "Envelope4_DelayBpmSync"
        iEnvelope4_AttackBpmSync_indx chnget  "iEnvelope4_AttackBpmSync"
        kEnvelope4_AttackBpmSync table iEnvelope4_AttackBpmSync_indx, giSinglePreset
        chnset kEnvelope4_AttackBpmSync, "Envelope4_AttackBpmSync"
        iEnvelope4_DecayBpmSync_indx chnget  "iEnvelope4_DecayBpmSync"
        kEnvelope4_DecayBpmSync table iEnvelope4_DecayBpmSync_indx, giSinglePreset
        chnset kEnvelope4_DecayBpmSync, "Envelope4_DecayBpmSync"
        iEnvelope4_ReleaseBpmSync_indx chnget  "iEnvelope4_ReleaseBpmSync"
        kEnvelope4_ReleaseBpmSync table iEnvelope4_ReleaseBpmSync_indx, giSinglePreset
        chnset kEnvelope4_ReleaseBpmSync, "Envelope4_ReleaseBpmSync"
        iRandh1_FreqBpmSync_indx chnget  "iRandh1_FreqBpmSync"
        kRandh1_FreqBpmSync table iRandh1_FreqBpmSync_indx, giSinglePreset
        chnset kRandh1_FreqBpmSync, "Randh1_FreqBpmSync"
        iRandh2_FreqBpmSync_indx chnget  "iRandh2_FreqBpmSync"
        kRandh2_FreqBpmSync table iRandh2_FreqBpmSync_indx, giSinglePreset
        chnset kRandh2_FreqBpmSync, "Randh2_FreqBpmSync"