/*

    Copyright (C) 2010 Oeyvind Brandtsegg and Partikkelaudio.com

    This file is part of the Hadron Particle Synthesizer.

    The Hadron Particle Synthesizer is free software; you can redistribute it
    and/or modify it under the terms of the GNU Lesser General Public
    License, version 3.0, as published by the Free Software Foundation.

    Hadron Particle Synthesizer is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with Hadron Particle Synthesizer; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
    02111-1307 USA
*/

; modulator numbers stored as values in table giModulators
        chnset  0,  "iLFO1"
        chnset  1,  "iLFO2"
        chnset  2,  "iLFO3"
        chnset  3,  "iLFO4"
        chnset  4,  "iEnvelope1"
        chnset  5,  "iEnvelope2"
        chnset  6,  "iEnvelope3"
        chnset  7,  "iEnvelope4"
        chnset  8,  "iRandh1"
        chnset  9,  "iRandh2"
        chnset  10, "iRspline1"
        chnset  11, "iRspline2"
        chnset  12, "iDivider1"
        chnset  13, "iDivider2"
        chnset  14, "iDivider3"
        chnset  15, "iDivider4"
        chnset  16, "iModulo1"
        chnset  17, "iMultiplier1"
        chnset  18, "iMultiplier2"
        chnset  19, "iFunc1"
        chnset  20, "iFunc2"
        chnset  21, "iFunc3"
        chnset  22, "iFunc4"
        chnset  23, "iAmpAnalysis1"
        chnset  24, "iCpsAnalysis1"
        chnset  25, "iTransientAnalysis1"
        chnset  26, "iTransientEnvelope1"
        chnset  27, "iAmpAnalysis2"
        chnset  28, "iCpsAnalysis2"
        chnset  29, "iTransientAnalysis2"
        chnset  30, "iTransientEnvelope2"
        chnset  31, "iAmpAnalysis3"
        chnset  32, "iCpsAnalysis3"
        chnset  33, "iTransientAnalysis3"
        chnset  34, "iTransientEnvelope3"
        chnset  35, "iAmpAnalysis4"
        chnset  36, "iCpsAnalysis4"
        chnset  37, "iTransientAnalysis4"
        chnset  38, "iTransientEnvelope4"
        chnset  39, "iSoundLength1"     
        chnset  40, "iSoundLength2"     
        chnset  41, "iSoundLength3"     
        chnset  42, "iSoundLength4"     
        chnset  43, "iMidiCtrl1"
        chnset  44, "iMidiCtrl2"
        chnset  45, "iMidiCtrl3"
        chnset  46, "iMidiCtrl4"
        chnset  47, "iMidiNoteCps"
        chnset  48, "iMidiNoteNum"
        chnset  49, "iMidiNoteVel"
        chnset  50, "iMidiNoteAmp"
        chnset  51, "iMidiNoteInterval"


